name: Spring Boot CI/CD with Docker Hub

on:
  push:
    branches: [ "main" ]   # chạy pipeline khi push lên main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Cài đặt JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # hoặc 'zulu', 'corretto' đều được
          java-version: '17'

      # 3. Build Spring Boot (bỏ test nếu cần)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Upload artifact (optional)
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 5. Login Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 6. Build Docker image
      - name: Build Docker image
        run: docker build -t baphuoc03/spring-boot-app:latest .

      # 7. Push Docker image
      - name: Push to Docker Hub
        run: docker push baphuoc03/spring-boot-app:latest
